
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("74f0806c-5fac-4642-9cb0-751d47517a2e")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("AdventureWorksModel", "FK_VendorAddress_Address_AddressID", "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Address), "VendorAddress", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VendorAddress), True)>
<Assembly: EdmRelationshipAttribute("AdventureWorksModel", "FK_ProductVendor_Product_ProductID", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Product), "ProductVendor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ProductVendor), True)>
<Assembly: EdmRelationshipAttribute("AdventureWorksModel", "FK_ProductVendor_Vendor_VendorID", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Vendor), "ProductVendor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(ProductVendor), True)>
<Assembly: EdmRelationshipAttribute("AdventureWorksModel", "FK_VendorAddress_Vendor_VendorID", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Vendor), "VendorAddress", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VendorAddress), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class AWEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new AWEntities object using the connection string found in the 'AWEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=AWEntities", "AWEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = false
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new AWEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "AWEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = false
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new AWEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "AWEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = false
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Address() As ObjectSet(Of Address)
        Get
            If (_Address Is Nothing) Then
                _Address = MyBase.CreateObjectSet(Of Address)("Address")
            End If
            Return _Address
        End Get
    End Property

    Private _Address As ObjectSet(Of Address)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Product() As ObjectSet(Of Product)
        Get
            If (_Product Is Nothing) Then
                _Product = MyBase.CreateObjectSet(Of Product)("Product")
            End If
            Return _Product
        End Get
    End Property

    Private _Product As ObjectSet(Of Product)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ProductVendor() As ObjectSet(Of ProductVendor)
        Get
            If (_ProductVendor Is Nothing) Then
                _ProductVendor = MyBase.CreateObjectSet(Of ProductVendor)("ProductVendor")
            End If
            Return _ProductVendor
        End Get
    End Property

    Private _ProductVendor As ObjectSet(Of ProductVendor)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Vendor() As ObjectSet(Of Vendor)
        Get
            If (_Vendor Is Nothing) Then
                _Vendor = MyBase.CreateObjectSet(Of Vendor)("Vendor")
            End If
            Return _Vendor
        End Get
    End Property

    Private _Vendor As ObjectSet(Of Vendor)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property VendorAddress() As ObjectSet(Of VendorAddress)
        Get
            If (_VendorAddress Is Nothing) Then
                _VendorAddress = MyBase.CreateObjectSet(Of VendorAddress)("VendorAddress")
            End If
            Return _VendorAddress
        End Get
    End Property

    Private _VendorAddress As ObjectSet(Of VendorAddress)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Address EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAddress(ByVal address As Address)
        MyBase.AddObject("Address", address)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Product EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProduct(ByVal product As Product)
        MyBase.AddObject("Product", product)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ProductVendor EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProductVendor(ByVal productVendor As ProductVendor)
        MyBase.AddObject("ProductVendor", productVendor)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Vendor EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVendor(ByVal vendor As Vendor)
        MyBase.AddObject("Vendor", vendor)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the VendorAddress EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVendorAddress(ByVal vendorAddress As VendorAddress)
        MyBase.AddObject("VendorAddress", vendorAddress)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="Address")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Address
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Address object.
    ''' </summary>
    ''' <param name="addressID">Initial value of the AddressID property.</param>
    ''' <param name="addressLine1">Initial value of the AddressLine1 property.</param>
    ''' <param name="city">Initial value of the City property.</param>
    ''' <param name="stateProvinceID">Initial value of the StateProvinceID property.</param>
    ''' <param name="postalCode">Initial value of the PostalCode property.</param>
    ''' <param name="rowguid">Initial value of the rowguid property.</param>
    ''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
    Public Shared Function CreateAddress(addressID As Global.System.Int32, addressLine1 As Global.System.String, city As Global.System.String, stateProvinceID As Global.System.Int32, postalCode As Global.System.String, rowguid As Global.System.Guid, modifiedDate As Global.System.DateTime) As Address
        Dim address as Address = New Address
        address.AddressID = addressID
        address.AddressLine1 = addressLine1
        address.City = city
        address.StateProvinceID = stateProvinceID
        address.PostalCode = postalCode
        address.rowguid = rowguid
        address.ModifiedDate = modifiedDate
        Return address
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressID() As Global.System.Int32
        Get
            Return _AddressID
        End Get
        Set
            If (_AddressID <> Value) Then
                OnAddressIDChanging(value)
                ReportPropertyChanging("AddressID")
                _AddressID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("AddressID")
                OnAddressIDChanged()
            End If
        End Set
    End Property

    Private _AddressID As Global.System.Int32
    Private Partial Sub OnAddressIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAddressIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressLine1() As Global.System.String
        Get
            Return _AddressLine1
        End Get
        Set
            OnAddressLine1Changing(value)
            ReportPropertyChanging("AddressLine1")
            _AddressLine1 = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AddressLine1")
            OnAddressLine1Changed()
        End Set
    End Property

    Private _AddressLine1 As Global.System.String
    Private Partial Sub OnAddressLine1Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressLine1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AddressLine2() As Global.System.String
        Get
            Return _AddressLine2
        End Get
        Set
            OnAddressLine2Changing(value)
            ReportPropertyChanging("AddressLine2")
            _AddressLine2 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("AddressLine2")
            OnAddressLine2Changed()
        End Set
    End Property

    Private _AddressLine2 As Global.System.String
    Private Partial Sub OnAddressLine2Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressLine2Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StateProvinceID() As Global.System.Int32
        Get
            Return _StateProvinceID
        End Get
        Set
            OnStateProvinceIDChanging(value)
            ReportPropertyChanging("StateProvinceID")
            _StateProvinceID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StateProvinceID")
            OnStateProvinceIDChanged()
        End Set
    End Property

    Private _StateProvinceID As Global.System.Int32
    Private Partial Sub OnStateProvinceIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnStateProvinceIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PostalCode() As Global.System.String
        Get
            Return _PostalCode
        End Get
        Set
            OnPostalCodeChanging(value)
            ReportPropertyChanging("PostalCode")
            _PostalCode = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("PostalCode")
            OnPostalCodeChanged()
        End Set
    End Property

    Private _PostalCode As Global.System.String
    Private Partial Sub OnPostalCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPostalCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property rowguid() As Global.System.Guid
        Get
            Return _rowguid
        End Get
        Set
            OnrowguidChanging(value)
            ReportPropertyChanging("rowguid")
            _rowguid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("rowguid")
            OnrowguidChanged()
        End Set
    End Property

    Private _rowguid As Global.System.Guid
    Private Partial Sub OnrowguidChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnrowguidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModifiedDate() As Global.System.DateTime
        Get
            Return _ModifiedDate
        End Get
        Set
            OnModifiedDateChanging(value)
            ReportPropertyChanging("ModifiedDate")
            _ModifiedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModifiedDate")
            OnModifiedDateChanged()
        End Set
    End Property

    Private _ModifiedDate As Global.System.DateTime
    Private Partial Sub OnModifiedDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnModifiedDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property AddressLine3() As Global.System.String
        Get
            Return _AddressLine3
        End Get
        Set
            OnAddressLine3Changing(value)
            ReportPropertyChanging("AddressLine3")
            _AddressLine3 = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("AddressLine3")
            OnAddressLine3Changed()
        End Set
    End Property

    Private _AddressLine3 As Global.System.String
    Private Partial Sub OnAddressLine3Changing(value As Global.System.String)
    End Sub

    Private Partial Sub OnAddressLine3Changed()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_VendorAddress_Address_AddressID", "VendorAddress")>
     Public Property VendorAddress() As EntityCollection(Of VendorAddress)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VendorAddress)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "VendorAddress")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VendorAddress)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "VendorAddress", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Product object.
    ''' </summary>
    ''' <param name="productID">Initial value of the ProductID property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="productNumber">Initial value of the ProductNumber property.</param>
    ''' <param name="makeFlag">Initial value of the MakeFlag property.</param>
    ''' <param name="finishedGoodsFlag">Initial value of the FinishedGoodsFlag property.</param>
    ''' <param name="safetyStockLevel">Initial value of the SafetyStockLevel property.</param>
    ''' <param name="reorderPoint">Initial value of the ReorderPoint property.</param>
    ''' <param name="standardCost">Initial value of the StandardCost property.</param>
    ''' <param name="listPrice">Initial value of the ListPrice property.</param>
    ''' <param name="daysToManufacture">Initial value of the DaysToManufacture property.</param>
    ''' <param name="sellStartDate">Initial value of the SellStartDate property.</param>
    ''' <param name="rowguid">Initial value of the rowguid property.</param>
    ''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
    Public Shared Function CreateProduct(productID As Global.System.Int32, name As Global.System.String, productNumber As Global.System.String, makeFlag As Global.System.Boolean, finishedGoodsFlag As Global.System.Boolean, safetyStockLevel As Global.System.Int16, reorderPoint As Global.System.Int16, standardCost As Global.System.Decimal, listPrice As Global.System.Decimal, daysToManufacture As Global.System.Int32, sellStartDate As Global.System.DateTime, rowguid As Global.System.Guid, modifiedDate As Global.System.DateTime) As Product
        Dim product as Product = New Product
        product.ProductID = productID
        product.Name = name
        product.ProductNumber = productNumber
        product.MakeFlag = makeFlag
        product.FinishedGoodsFlag = finishedGoodsFlag
        product.SafetyStockLevel = safetyStockLevel
        product.ReorderPoint = reorderPoint
        product.StandardCost = standardCost
        product.ListPrice = listPrice
        product.DaysToManufacture = daysToManufacture
        product.SellStartDate = sellStartDate
        product.rowguid = rowguid
        product.ModifiedDate = modifiedDate
        Return product
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductID() As Global.System.Int32
        Get
            Return _ProductID
        End Get
        Set
            If (_ProductID <> Value) Then
                OnProductIDChanging(value)
                ReportPropertyChanging("ProductID")
                _ProductID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProductID")
                OnProductIDChanged()
            End If
        End Set
    End Property

    Private _ProductID As Global.System.Int32
    Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProductIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductNumber() As Global.System.String
        Get
            Return _ProductNumber
        End Get
        Set
            OnProductNumberChanging(value)
            ReportPropertyChanging("ProductNumber")
            _ProductNumber = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("ProductNumber")
            OnProductNumberChanged()
        End Set
    End Property

    Private _ProductNumber As Global.System.String
    Private Partial Sub OnProductNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MakeFlag() As Global.System.Boolean
        Get
            Return _MakeFlag
        End Get
        Set
            OnMakeFlagChanging(value)
            ReportPropertyChanging("MakeFlag")
            _MakeFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MakeFlag")
            OnMakeFlagChanged()
        End Set
    End Property

    Private _MakeFlag As Global.System.Boolean
    Private Partial Sub OnMakeFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnMakeFlagChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FinishedGoodsFlag() As Global.System.Boolean
        Get
            Return _FinishedGoodsFlag
        End Get
        Set
            OnFinishedGoodsFlagChanging(value)
            ReportPropertyChanging("FinishedGoodsFlag")
            _FinishedGoodsFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FinishedGoodsFlag")
            OnFinishedGoodsFlagChanged()
        End Set
    End Property

    Private _FinishedGoodsFlag As Global.System.Boolean
    Private Partial Sub OnFinishedGoodsFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnFinishedGoodsFlagChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Color() As Global.System.String
        Get
            Return _Color
        End Get
        Set
            OnColorChanging(value)
            ReportPropertyChanging("Color")
            _Color = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Color")
            OnColorChanged()
        End Set
    End Property

    Private _Color As Global.System.String
    Private Partial Sub OnColorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnColorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SafetyStockLevel() As Global.System.Int16
        Get
            Return _SafetyStockLevel
        End Get
        Set
            OnSafetyStockLevelChanging(value)
            ReportPropertyChanging("SafetyStockLevel")
            _SafetyStockLevel = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SafetyStockLevel")
            OnSafetyStockLevelChanged()
        End Set
    End Property

    Private _SafetyStockLevel As Global.System.Int16
    Private Partial Sub OnSafetyStockLevelChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnSafetyStockLevelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ReorderPoint() As Global.System.Int16
        Get
            Return _ReorderPoint
        End Get
        Set
            OnReorderPointChanging(value)
            ReportPropertyChanging("ReorderPoint")
            _ReorderPoint = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ReorderPoint")
            OnReorderPointChanged()
        End Set
    End Property

    Private _ReorderPoint As Global.System.Int16
    Private Partial Sub OnReorderPointChanging(value As Global.System.Int16)
    End Sub

    Private Partial Sub OnReorderPointChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StandardCost() As Global.System.Decimal
        Get
            Return _StandardCost
        End Get
        Set
            OnStandardCostChanging(value)
            ReportPropertyChanging("StandardCost")
            _StandardCost = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StandardCost")
            OnStandardCostChanged()
        End Set
    End Property

    Private _StandardCost As Global.System.Decimal
    Private Partial Sub OnStandardCostChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnStandardCostChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ListPrice() As Global.System.Decimal
        Get
            Return _ListPrice
        End Get
        Set
            OnListPriceChanging(value)
            ReportPropertyChanging("ListPrice")
            _ListPrice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ListPrice")
            OnListPriceChanged()
        End Set
    End Property

    Private _ListPrice As Global.System.Decimal
    Private Partial Sub OnListPriceChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnListPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Size() As Global.System.String
        Get
            Return _Size
        End Get
        Set
            OnSizeChanging(value)
            ReportPropertyChanging("Size")
            _Size = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Size")
            OnSizeChanged()
        End Set
    End Property

    Private _Size As Global.System.String
    Private Partial Sub OnSizeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSizeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SizeUnitMeasureCode() As Global.System.String
        Get
            Return _SizeUnitMeasureCode
        End Get
        Set
            OnSizeUnitMeasureCodeChanging(value)
            ReportPropertyChanging("SizeUnitMeasureCode")
            _SizeUnitMeasureCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("SizeUnitMeasureCode")
            OnSizeUnitMeasureCodeChanged()
        End Set
    End Property

    Private _SizeUnitMeasureCode As Global.System.String
    Private Partial Sub OnSizeUnitMeasureCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSizeUnitMeasureCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property WeightUnitMeasureCode() As Global.System.String
        Get
            Return _WeightUnitMeasureCode
        End Get
        Set
            OnWeightUnitMeasureCodeChanging(value)
            ReportPropertyChanging("WeightUnitMeasureCode")
            _WeightUnitMeasureCode = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("WeightUnitMeasureCode")
            OnWeightUnitMeasureCodeChanged()
        End Set
    End Property

    Private _WeightUnitMeasureCode As Global.System.String
    Private Partial Sub OnWeightUnitMeasureCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnWeightUnitMeasureCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Weight() As Nullable(Of Global.System.Decimal)
        Get
            Return _Weight
        End Get
        Set
            OnWeightChanging(value)
            ReportPropertyChanging("Weight")
            _Weight = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Weight")
            OnWeightChanged()
        End Set
    End Property

    Private _Weight As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnWeightChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnWeightChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DaysToManufacture() As Global.System.Int32
        Get
            Return _DaysToManufacture
        End Get
        Set
            OnDaysToManufactureChanging(value)
            ReportPropertyChanging("DaysToManufacture")
            _DaysToManufacture = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DaysToManufacture")
            OnDaysToManufactureChanged()
        End Set
    End Property

    Private _DaysToManufacture As Global.System.Int32
    Private Partial Sub OnDaysToManufactureChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDaysToManufactureChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductLine() As Global.System.String
        Get
            Return _ProductLine
        End Get
        Set
            OnProductLineChanging(value)
            ReportPropertyChanging("ProductLine")
            _ProductLine = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ProductLine")
            OnProductLineChanged()
        End Set
    End Property

    Private _ProductLine As Global.System.String
    Private Partial Sub OnProductLineChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProductLineChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property [Class]() As Global.System.String
        Get
            Return _Class
        End Get
        Set
            OnClassChanging(value)
            ReportPropertyChanging("Class")
            _Class = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Class")
            OnClassChanged()
        End Set
    End Property

    Private _Class As Global.System.String
    Private Partial Sub OnClassChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnClassChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Style() As Global.System.String
        Get
            Return _Style
        End Get
        Set
            OnStyleChanging(value)
            ReportPropertyChanging("Style")
            _Style = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Style")
            OnStyleChanged()
        End Set
    End Property

    Private _Style As Global.System.String
    Private Partial Sub OnStyleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStyleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductSubcategoryID() As Nullable(Of Global.System.Int32)
        Get
            Return _ProductSubcategoryID
        End Get
        Set
            OnProductSubcategoryIDChanging(value)
            ReportPropertyChanging("ProductSubcategoryID")
            _ProductSubcategoryID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ProductSubcategoryID")
            OnProductSubcategoryIDChanged()
        End Set
    End Property

    Private _ProductSubcategoryID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnProductSubcategoryIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnProductSubcategoryIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ProductModelID() As Nullable(Of Global.System.Int32)
        Get
            Return _ProductModelID
        End Get
        Set
            OnProductModelIDChanging(value)
            ReportPropertyChanging("ProductModelID")
            _ProductModelID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ProductModelID")
            OnProductModelIDChanged()
        End Set
    End Property

    Private _ProductModelID As Nullable(Of Global.System.Int32)
    Private Partial Sub OnProductModelIDChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnProductModelIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SellStartDate() As Global.System.DateTime
        Get
            Return _SellStartDate
        End Get
        Set
            OnSellStartDateChanging(value)
            ReportPropertyChanging("SellStartDate")
            _SellStartDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SellStartDate")
            OnSellStartDateChanged()
        End Set
    End Property

    Private _SellStartDate As Global.System.DateTime
    Private Partial Sub OnSellStartDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnSellStartDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SellEndDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _SellEndDate
        End Get
        Set
            OnSellEndDateChanging(value)
            ReportPropertyChanging("SellEndDate")
            _SellEndDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SellEndDate")
            OnSellEndDateChanged()
        End Set
    End Property

    Private _SellEndDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnSellEndDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnSellEndDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DiscontinuedDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _DiscontinuedDate
        End Get
        Set
            OnDiscontinuedDateChanging(value)
            ReportPropertyChanging("DiscontinuedDate")
            _DiscontinuedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DiscontinuedDate")
            OnDiscontinuedDateChanged()
        End Set
    End Property

    Private _DiscontinuedDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDiscontinuedDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDiscontinuedDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property rowguid() As Global.System.Guid
        Get
            Return _rowguid
        End Get
        Set
            OnrowguidChanging(value)
            ReportPropertyChanging("rowguid")
            _rowguid = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("rowguid")
            OnrowguidChanged()
        End Set
    End Property

    Private _rowguid As Global.System.Guid
    Private Partial Sub OnrowguidChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnrowguidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModifiedDate() As Global.System.DateTime
        Get
            Return _ModifiedDate
        End Get
        Set
            OnModifiedDateChanging(value)
            ReportPropertyChanging("ModifiedDate")
            _ModifiedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModifiedDate")
            OnModifiedDateChanged()
        End Set
    End Property

    Private _ModifiedDate As Global.System.DateTime
    Private Partial Sub OnModifiedDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnModifiedDateChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_ProductVendor_Product_ProductID", "ProductVendor")>
     Public Property ProductVendor() As EntityCollection(Of ProductVendor)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ProductVendor)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "ProductVendor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ProductVendor)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "ProductVendor", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="ProductVendor")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ProductVendor
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ProductVendor object.
    ''' </summary>
    ''' <param name="productID">Initial value of the ProductID property.</param>
    ''' <param name="vendorID">Initial value of the VendorID property.</param>
    ''' <param name="averageLeadTime">Initial value of the AverageLeadTime property.</param>
    ''' <param name="standardPrice">Initial value of the StandardPrice property.</param>
    ''' <param name="minOrderQty">Initial value of the MinOrderQty property.</param>
    ''' <param name="maxOrderQty">Initial value of the MaxOrderQty property.</param>
    ''' <param name="unitMeasureCode">Initial value of the UnitMeasureCode property.</param>
    ''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
    Public Shared Function CreateProductVendor(productID As Global.System.Int32, vendorID As Global.System.Int32, averageLeadTime As Global.System.Int32, standardPrice As Global.System.Decimal, minOrderQty As Global.System.Int32, maxOrderQty As Global.System.Int32, unitMeasureCode As Global.System.String, modifiedDate As Global.System.DateTime) As ProductVendor
        Dim productVendor as ProductVendor = New ProductVendor
        productVendor.ProductID = productID
        productVendor.VendorID = vendorID
        productVendor.AverageLeadTime = averageLeadTime
        productVendor.StandardPrice = standardPrice
        productVendor.MinOrderQty = minOrderQty
        productVendor.MaxOrderQty = maxOrderQty
        productVendor.UnitMeasureCode = unitMeasureCode
        productVendor.ModifiedDate = modifiedDate
        Return productVendor
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductID() As Global.System.Int32
        Get
            Return _ProductID
        End Get
        Set
            If (_ProductID <> Value) Then
                OnProductIDChanging(value)
                ReportPropertyChanging("ProductID")
                _ProductID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProductID")
                OnProductIDChanged()
            End If
        End Set
    End Property

    Private _ProductID As Global.System.Int32
    Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProductIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VendorID() As Global.System.Int32
        Get
            Return _VendorID
        End Get
        Set
            If (_VendorID <> Value) Then
                OnVendorIDChanging(value)
                ReportPropertyChanging("VendorID")
                _VendorID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("VendorID")
                OnVendorIDChanged()
            End If
        End Set
    End Property

    Private _VendorID As Global.System.Int32
    Private Partial Sub OnVendorIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnVendorIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AverageLeadTime() As Global.System.Int32
        Get
            Return _AverageLeadTime
        End Get
        Set
            OnAverageLeadTimeChanging(value)
            ReportPropertyChanging("AverageLeadTime")
            _AverageLeadTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AverageLeadTime")
            OnAverageLeadTimeChanged()
        End Set
    End Property

    Private _AverageLeadTime As Global.System.Int32
    Private Partial Sub OnAverageLeadTimeChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAverageLeadTimeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property StandardPrice() As Global.System.Decimal
        Get
            Return _StandardPrice
        End Get
        Set
            OnStandardPriceChanging(value)
            ReportPropertyChanging("StandardPrice")
            _StandardPrice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StandardPrice")
            OnStandardPriceChanged()
        End Set
    End Property

    Private _StandardPrice As Global.System.Decimal
    Private Partial Sub OnStandardPriceChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnStandardPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastReceiptCost() As Nullable(Of Global.System.Decimal)
        Get
            Return _LastReceiptCost
        End Get
        Set
            OnLastReceiptCostChanging(value)
            ReportPropertyChanging("LastReceiptCost")
            _LastReceiptCost = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastReceiptCost")
            OnLastReceiptCostChanged()
        End Set
    End Property

    Private _LastReceiptCost As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLastReceiptCostChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLastReceiptCostChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastReceiptDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastReceiptDate
        End Get
        Set
            OnLastReceiptDateChanging(value)
            ReportPropertyChanging("LastReceiptDate")
            _LastReceiptDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastReceiptDate")
            OnLastReceiptDateChanged()
        End Set
    End Property

    Private _LastReceiptDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastReceiptDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastReceiptDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MinOrderQty() As Global.System.Int32
        Get
            Return _MinOrderQty
        End Get
        Set
            OnMinOrderQtyChanging(value)
            ReportPropertyChanging("MinOrderQty")
            _MinOrderQty = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MinOrderQty")
            OnMinOrderQtyChanged()
        End Set
    End Property

    Private _MinOrderQty As Global.System.Int32
    Private Partial Sub OnMinOrderQtyChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMinOrderQtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MaxOrderQty() As Global.System.Int32
        Get
            Return _MaxOrderQty
        End Get
        Set
            OnMaxOrderQtyChanging(value)
            ReportPropertyChanging("MaxOrderQty")
            _MaxOrderQty = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("MaxOrderQty")
            OnMaxOrderQtyChanged()
        End Set
    End Property

    Private _MaxOrderQty As Global.System.Int32
    Private Partial Sub OnMaxOrderQtyChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMaxOrderQtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OnOrderQty() As Nullable(Of Global.System.Int32)
        Get
            Return _OnOrderQty
        End Get
        Set
            OnOnOrderQtyChanging(value)
            ReportPropertyChanging("OnOrderQty")
            _OnOrderQty = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OnOrderQty")
            OnOnOrderQtyChanged()
        End Set
    End Property

    Private _OnOrderQty As Nullable(Of Global.System.Int32)
    Private Partial Sub OnOnOrderQtyChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnOnOrderQtyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UnitMeasureCode() As Global.System.String
        Get
            Return _UnitMeasureCode
        End Get
        Set
            OnUnitMeasureCodeChanging(value)
            ReportPropertyChanging("UnitMeasureCode")
            _UnitMeasureCode = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("UnitMeasureCode")
            OnUnitMeasureCodeChanged()
        End Set
    End Property

    Private _UnitMeasureCode As Global.System.String
    Private Partial Sub OnUnitMeasureCodeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUnitMeasureCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModifiedDate() As Global.System.DateTime
        Get
            Return _ModifiedDate
        End Get
        Set
            OnModifiedDateChanging(value)
            ReportPropertyChanging("ModifiedDate")
            _ModifiedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModifiedDate")
            OnModifiedDateChanged()
        End Set
    End Property

    Private _ModifiedDate As Global.System.DateTime
    Private Partial Sub OnModifiedDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnModifiedDateChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_ProductVendor_Product_ProductID", "Product")>
    Public Property Product() As Product
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "Product").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "Product").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductReference() As EntityReference(Of Product)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "Product")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("AdventureWorksModel.FK_ProductVendor_Product_ProductID", "Product", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_ProductVendor_Vendor_VendorID", "Vendor")>
    Public Property Vendor() As Vendor
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "Vendor").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "Vendor").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property VendorReference() As EntityReference(Of Vendor)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "Vendor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Vendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "Vendor", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="Vendor")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Vendor
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Vendor object.
    ''' </summary>
    ''' <param name="vendorID">Initial value of the VendorID property.</param>
    ''' <param name="accountNumber">Initial value of the AccountNumber property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="creditRating">Initial value of the CreditRating property.</param>
    ''' <param name="preferredVendorStatus">Initial value of the PreferredVendorStatus property.</param>
    ''' <param name="activeFlag">Initial value of the ActiveFlag property.</param>
    ''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
    Public Shared Function CreateVendor(vendorID As Global.System.Int32, accountNumber As Global.System.String, name As Global.System.String, creditRating As Global.System.Byte, preferredVendorStatus As Global.System.Boolean, activeFlag As Global.System.Boolean, modifiedDate As Global.System.DateTime) As Vendor
        Dim vendor as Vendor = New Vendor
        vendor.VendorID = vendorID
        vendor.AccountNumber = accountNumber
        vendor.Name = name
        vendor.CreditRating = creditRating
        vendor.PreferredVendorStatus = preferredVendorStatus
        vendor.ActiveFlag = activeFlag
        vendor.ModifiedDate = modifiedDate
        Return vendor
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VendorID() As Global.System.Int32
        Get
            Return _VendorID
        End Get
        Set
            If (_VendorID <> Value) Then
                OnVendorIDChanging(value)
                ReportPropertyChanging("VendorID")
                _VendorID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("VendorID")
                OnVendorIDChanged()
            End If
        End Set
    End Property

    Private _VendorID As Global.System.Int32
    Private Partial Sub OnVendorIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnVendorIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AccountNumber() As Global.System.String
        Get
            Return _AccountNumber
        End Get
        Set
            OnAccountNumberChanging(value)
            ReportPropertyChanging("AccountNumber")
            _AccountNumber = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AccountNumber")
            OnAccountNumberChanged()
        End Set
    End Property

    Private _AccountNumber As Global.System.String
    Private Partial Sub OnAccountNumberChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAccountNumberChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CreditRating() As Global.System.Byte
        Get
            Return _CreditRating
        End Get
        Set
            OnCreditRatingChanging(value)
            ReportPropertyChanging("CreditRating")
            _CreditRating = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CreditRating")
            OnCreditRatingChanged()
        End Set
    End Property

    Private _CreditRating As Global.System.Byte
    Private Partial Sub OnCreditRatingChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnCreditRatingChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PreferredVendorStatus() As Global.System.Boolean
        Get
            Return _PreferredVendorStatus
        End Get
        Set
            OnPreferredVendorStatusChanging(value)
            ReportPropertyChanging("PreferredVendorStatus")
            _PreferredVendorStatus = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PreferredVendorStatus")
            OnPreferredVendorStatusChanged()
        End Set
    End Property

    Private _PreferredVendorStatus As Global.System.Boolean
    Private Partial Sub OnPreferredVendorStatusChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnPreferredVendorStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ActiveFlag() As Global.System.Boolean
        Get
            Return _ActiveFlag
        End Get
        Set
            OnActiveFlagChanging(value)
            ReportPropertyChanging("ActiveFlag")
            _ActiveFlag = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ActiveFlag")
            OnActiveFlagChanged()
        End Set
    End Property

    Private _ActiveFlag As Global.System.Boolean
    Private Partial Sub OnActiveFlagChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnActiveFlagChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PurchasingWebServiceURL() As Global.System.String
        Get
            Return _PurchasingWebServiceURL
        End Get
        Set
            OnPurchasingWebServiceURLChanging(value)
            ReportPropertyChanging("PurchasingWebServiceURL")
            _PurchasingWebServiceURL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PurchasingWebServiceURL")
            OnPurchasingWebServiceURLChanged()
        End Set
    End Property

    Private _PurchasingWebServiceURL As Global.System.String
    Private Partial Sub OnPurchasingWebServiceURLChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPurchasingWebServiceURLChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModifiedDate() As Global.System.DateTime
        Get
            Return _ModifiedDate
        End Get
        Set
            OnModifiedDateChanging(value)
            ReportPropertyChanging("ModifiedDate")
            _ModifiedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModifiedDate")
            OnModifiedDateChanged()
        End Set
    End Property

    Private _ModifiedDate As Global.System.DateTime
    Private Partial Sub OnModifiedDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnModifiedDateChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_ProductVendor_Vendor_VendorID", "ProductVendor")>
     Public Property ProductVendor() As EntityCollection(Of ProductVendor)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of ProductVendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "ProductVendor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of ProductVendor)("AdventureWorksModel.FK_ProductVendor_Vendor_VendorID", "ProductVendor", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_VendorAddress_Vendor_VendorID", "VendorAddress")>
     Public Property VendorAddress() As EntityCollection(Of VendorAddress)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VendorAddress)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "VendorAddress")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VendorAddress)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "VendorAddress", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AdventureWorksModel", Name:="VendorAddress")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class VendorAddress
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new VendorAddress object.
    ''' </summary>
    ''' <param name="vendorID">Initial value of the VendorID property.</param>
    ''' <param name="addressID">Initial value of the AddressID property.</param>
    ''' <param name="addressTypeID">Initial value of the AddressTypeID property.</param>
    ''' <param name="modifiedDate">Initial value of the ModifiedDate property.</param>
    Public Shared Function CreateVendorAddress(vendorID As Global.System.Int32, addressID As Global.System.Int32, addressTypeID As Global.System.Int32, modifiedDate As Global.System.DateTime) As VendorAddress
        Dim vendorAddress as VendorAddress = New VendorAddress
        vendorAddress.VendorID = vendorID
        vendorAddress.AddressID = addressID
        vendorAddress.AddressTypeID = addressTypeID
        vendorAddress.ModifiedDate = modifiedDate
        Return vendorAddress
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VendorID() As Global.System.Int32
        Get
            Return _VendorID
        End Get
        Set
            If (_VendorID <> Value) Then
                OnVendorIDChanging(value)
                ReportPropertyChanging("VendorID")
                _VendorID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("VendorID")
                OnVendorIDChanged()
            End If
        End Set
    End Property

    Private _VendorID As Global.System.Int32
    Private Partial Sub OnVendorIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnVendorIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressID() As Global.System.Int32
        Get
            Return _AddressID
        End Get
        Set
            If (_AddressID <> Value) Then
                OnAddressIDChanging(value)
                ReportPropertyChanging("AddressID")
                _AddressID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("AddressID")
                OnAddressIDChanged()
            End If
        End Set
    End Property

    Private _AddressID As Global.System.Int32
    Private Partial Sub OnAddressIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAddressIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AddressTypeID() As Global.System.Int32
        Get
            Return _AddressTypeID
        End Get
        Set
            OnAddressTypeIDChanging(value)
            ReportPropertyChanging("AddressTypeID")
            _AddressTypeID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AddressTypeID")
            OnAddressTypeIDChanged()
        End Set
    End Property

    Private _AddressTypeID As Global.System.Int32
    Private Partial Sub OnAddressTypeIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAddressTypeIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ModifiedDate() As Global.System.DateTime
        Get
            Return _ModifiedDate
        End Get
        Set
            OnModifiedDateChanging(value)
            ReportPropertyChanging("ModifiedDate")
            _ModifiedDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ModifiedDate")
            OnModifiedDateChanged()
        End Set
    End Property

    Private _ModifiedDate As Global.System.DateTime
    Private Partial Sub OnModifiedDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnModifiedDateChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_VendorAddress_Address_AddressID", "Address")>
    Public Property Address() As Address
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Address)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "Address").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Address)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "Address").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AddressReference() As EntityReference(Of Address)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Address)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "Address")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Address)("AdventureWorksModel.FK_VendorAddress_Address_AddressID", "Address", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AdventureWorksModel", "FK_VendorAddress_Vendor_VendorID", "Vendor")>
    Public Property Vendor() As Vendor
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "Vendor").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "Vendor").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property VendorReference() As EntityReference(Of Vendor)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendor)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "Vendor")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Vendor)("AdventureWorksModel.FK_VendorAddress_Vendor_VendorID", "Vendor", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

