
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("23cd0167-1e1c-4e82-8ecc-b756721de28d")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("modelFirst", "Projektleiter", "Projekte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Projekte), "Mitarbeiter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Mitarbeiter))>
<Assembly: EdmRelationshipAttribute("modelFirst", "MitarbeiterProjekt", "Projekte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Projekte), "Mitarbeiter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Mitarbeiter))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class modelFirstContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new modelFirstContainer object using the connection string found in the 'modelFirstContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=modelFirstContainer", "modelFirstContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new modelFirstContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "modelFirstContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new modelFirstContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "modelFirstContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Mitarbeiter() As ObjectSet(Of Mitarbeiter)
        Get
            If (_Mitarbeiter Is Nothing) Then
                _Mitarbeiter = MyBase.CreateObjectSet(Of Mitarbeiter)("Mitarbeiter")
            End If
            Return _Mitarbeiter
        End Get
    End Property

    Private _Mitarbeiter As ObjectSet(Of Mitarbeiter)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Projekte() As ObjectSet(Of Projekte)
        Get
            If (_Projekte Is Nothing) Then
                _Projekte = MyBase.CreateObjectSet(Of Projekte)("Projekte")
            End If
            Return _Projekte
        End Get
    End Property

    Private _Projekte As ObjectSet(Of Projekte)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Mitarbeiter EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMitarbeiter(ByVal mitarbeiter As Mitarbeiter)
        MyBase.AddObject("Mitarbeiter", mitarbeiter)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Projekte EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProjekte(ByVal projekte As Projekte)
        MyBase.AddObject("Projekte", projekte)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="modelFirst", Name:="Mitarbeiter")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Mitarbeiter
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Mitarbeiter object.
    ''' </summary>
    ''' <param name="mitarbeiterID">Initial value of the MitarbeiterID property.</param>
    ''' <param name="nachname">Initial value of the Nachname property.</param>
    ''' <param name="vorname">Initial value of the Vorname property.</param>
    ''' <param name="geburtstag">Initial value of the Geburtstag property.</param>
    ''' <param name="angestelltSeit">Initial value of the AngestelltSeit property.</param>
    Public Shared Function CreateMitarbeiter(mitarbeiterID As Global.System.Int32, nachname As Global.System.String, vorname As Global.System.String, geburtstag As Global.System.String, angestelltSeit As Global.System.String) As Mitarbeiter
        Dim mitarbeiter as Mitarbeiter = New Mitarbeiter
        mitarbeiter.MitarbeiterID = mitarbeiterID
        mitarbeiter.Nachname = nachname
        mitarbeiter.Vorname = vorname
        mitarbeiter.Geburtstag = geburtstag
        mitarbeiter.AngestelltSeit = angestelltSeit
        Return mitarbeiter
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MitarbeiterID() As Global.System.Int32
        Get
            Return _MitarbeiterID
        End Get
        Set
            If (_MitarbeiterID <> Value) Then
                OnMitarbeiterIDChanging(value)
                ReportPropertyChanging("MitarbeiterID")
                _MitarbeiterID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("MitarbeiterID")
                OnMitarbeiterIDChanged()
            End If
        End Set
    End Property

    Private _MitarbeiterID As Global.System.Int32
    Private Partial Sub OnMitarbeiterIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMitarbeiterIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nachname() As Global.System.String
        Get
            Return _Nachname
        End Get
        Set
            OnNachnameChanging(value)
            ReportPropertyChanging("Nachname")
            _Nachname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nachname")
            OnNachnameChanged()
        End Set
    End Property

    Private _Nachname As Global.System.String
    Private Partial Sub OnNachnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNachnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Vorname() As Global.System.String
        Get
            Return _Vorname
        End Get
        Set
            OnVornameChanging(value)
            ReportPropertyChanging("Vorname")
            _Vorname = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Vorname")
            OnVornameChanged()
        End Set
    End Property

    Private _Vorname As Global.System.String
    Private Partial Sub OnVornameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVornameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Geburtstag() As Global.System.String
        Get
            Return _Geburtstag
        End Get
        Set
            OnGeburtstagChanging(value)
            ReportPropertyChanging("Geburtstag")
            _Geburtstag = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Geburtstag")
            OnGeburtstagChanged()
        End Set
    End Property

    Private _Geburtstag As Global.System.String
    Private Partial Sub OnGeburtstagChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGeburtstagChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AngestelltSeit() As Global.System.String
        Get
            Return _AngestelltSeit
        End Get
        Set
            OnAngestelltSeitChanging(value)
            ReportPropertyChanging("AngestelltSeit")
            _AngestelltSeit = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AngestelltSeit")
            OnAngestelltSeitChanged()
        End Set
    End Property

    Private _AngestelltSeit As Global.System.String
    Private Partial Sub OnAngestelltSeitChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAngestelltSeitChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("modelFirst", "Projektleiter", "Projekte")>
     Public Property Leitet() As EntityCollection(Of Projekte)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Projekte)("modelFirst.Projektleiter", "Projekte")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Projekte)("modelFirst.Projektleiter", "Projekte", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("modelFirst", "MitarbeiterProjekt", "Projekte")>
     Public Property MitarbeitAn() As EntityCollection(Of Projekte)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Projekte)("modelFirst.MitarbeiterProjekt", "Projekte")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Projekte)("modelFirst.MitarbeiterProjekt", "Projekte", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="modelFirst", Name:="Projekte")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Projekte
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Projekte object.
    ''' </summary>
    ''' <param name="projektID">Initial value of the ProjektID property.</param>
    ''' <param name="beschreibung">Initial value of the Beschreibung property.</param>
    ''' <param name="kostenstelle">Initial value of the Kostenstelle property.</param>
    Public Shared Function CreateProjekte(projektID As Global.System.Int32, beschreibung As Global.System.String, kostenstelle As Global.System.Int32) As Projekte
        Dim projekte as Projekte = New Projekte
        projekte.ProjektID = projektID
        projekte.Beschreibung = beschreibung
        projekte.Kostenstelle = kostenstelle
        Return projekte
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProjektID() As Global.System.Int32
        Get
            Return _ProjektID
        End Get
        Set
            If (_ProjektID <> Value) Then
                OnProjektIDChanging(value)
                ReportPropertyChanging("ProjektID")
                _ProjektID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProjektID")
                OnProjektIDChanged()
            End If
        End Set
    End Property

    Private _ProjektID As Global.System.Int32
    Private Partial Sub OnProjektIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnProjektIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Beschreibung() As Global.System.String
        Get
            Return _Beschreibung
        End Get
        Set
            OnBeschreibungChanging(value)
            ReportPropertyChanging("Beschreibung")
            _Beschreibung = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Beschreibung")
            OnBeschreibungChanged()
        End Set
    End Property

    Private _Beschreibung As Global.System.String
    Private Partial Sub OnBeschreibungChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnBeschreibungChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Kostenstelle() As Global.System.Int32
        Get
            Return _Kostenstelle
        End Get
        Set
            OnKostenstelleChanging(value)
            ReportPropertyChanging("Kostenstelle")
            _Kostenstelle = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Kostenstelle")
            OnKostenstelleChanged()
        End Set
    End Property

    Private _Kostenstelle As Global.System.Int32
    Private Partial Sub OnKostenstelleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnKostenstelleChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("modelFirst", "Projektleiter", "Mitarbeiter")>
    Public Property Leiter() As Mitarbeiter
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mitarbeiter)("modelFirst.Projektleiter", "Mitarbeiter").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mitarbeiter)("modelFirst.Projektleiter", "Mitarbeiter").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property LeiterReference() As EntityReference(Of Mitarbeiter)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Mitarbeiter)("modelFirst.Projektleiter", "Mitarbeiter")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Mitarbeiter)("modelFirst.Projektleiter", "Mitarbeiter", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("modelFirst", "MitarbeiterProjekt", "Mitarbeiter")>
     Public Property Mitarbeiter() As EntityCollection(Of Mitarbeiter)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Mitarbeiter)("modelFirst.MitarbeiterProjekt", "Mitarbeiter")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Mitarbeiter)("modelFirst.MitarbeiterProjekt", "Mitarbeiter", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

